# -*- coding: utf-8 -*-
"""groupedBarChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMZygyDzcRjoo5ubhNkUx8lu0N2qrPpa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def autolabel(rects, xpos='center'):
    ha = {'center': 'center', 'right': 'left', 'left': 'right'}
    offset = {'center': 0, 'right': 1, 'left': -1}
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{}'.format(height),
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(offset[xpos]*3, 3),
                    textcoords="offset points",
                    ha=ha[xpos], va='bottom')

def plotHeighWeight(dfCol, name, width = 0.25, nrows = 5, image_width = 12, image_height = 8):
# i = 0
# width = 0.25
# nrows = 5
# image_width = 12
# image_height = 8
# name = POS_LIST[i][46:-4]
# dfCol = pd.read_csv(POS_LIST[i])

    fig, ax = plt.subplots(figsize=(image_width, image_height))

    ind = np.arange(len(dfCol['age'][:nrows]))

    rects1 = ax.bar(ind - width/2, dfCol['age'][:nrows], width,
                    label='height')
    rects2 = ax.bar(ind + width/2, dfCol['overall'][:nrows], width,
                    label='weight')
    ax.set_ylabel('Age and Overall')
    ax.set_title(f'Position: {name}')
    ax.set_xticks(ind)
    ax.set_xticklabels(list(dfCol['short_name'])[:5])
    ax.legend()
    autolabel(rects1, "left")
    autolabel(rects2, "right")

    fig.tight_layout()

    plt.show()

POS_LIST = ["../../../datasets/Positionwise/centre_backs.csv",
"../../../datasets/Positionwise/free_roamers.csv",
"../../../datasets/Positionwise/full_backs.csv",
"../../../datasets/Positionwise/midfielders.csv",
"../../../datasets/Positionwise/strikers.csv",
"../../../datasets/Positionwise/wingers.csv"]
for i in range(len(POS_LIST)):
    plotHeighWeight(pd.read_csv(POS_LIST[i]), POS_LIST[i][46:-4])

